"""Auto-generated from https://github.com/etcd-io/etcd/issues/20340

Title: ETCD fails to start, with panic on 'failed to nodeToMember'
"""
from sregym.conductor.problems.generic_custom_build import GenericCustomBuildProblem


class AutoEtcd20340(GenericCustomBuildProblem):
    db_name   = "etcd"
    issue_url = "https://github.com/etcd-io/etcd/issues/20340"
    root_cause_description = (
        "ETCD fails to start, with panic on 'failed to nodeToMember'. ### Bug report criteria - [x] This bug report is not security related, security issues should be disclosed privately via security@etcd.io. - [x] This is not a support request or question, support requests or questions should be raised in the etcd [discussion forums](https://github.com/etcd-io/etcd/discussions). - [x] You have read the etcd [bug reporting guidelines](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/reporting_bugs.md). - [x] Existing open issues along with etcd [frequently asked questions](https://etcd.io/docs/latest/faq) have been checked and this is not a duplicate. ### What happened? During preparation for migration of default ETCD version in Talos, we prepared a patch with new version, to run against our test suite. The test suite _sometimes_"
    )
    reproducer = 'git clone https://github.com/shanduur/talos.git\ncd talos && git checkout test/etcd-3.6.x\n\n# prepare environment\ndocker buildx create --driver docker-container  --driver-opt network=host --name local1 --buildkitd-flags \'--allow-insecure-entitlement security.insecure\' --use\ndocker run -d -p 5005:5000 \\\n    --restart always \\\n    --name local registry:2\n\n# build necessary components\nmake installer-base IMAGE_REGISTRY=127.0.0.1:5005 PUSH=true\nmake imager IMAGE_REGISTRY=127.0.0.1:5005 PUSH=true\nmake installer IMAGE_REGISTRY=127.0.0.1:5005\n# Record installer image tag for the installation step\nmake initramfs kernel talosctl\n\n# start talos cluster\nbash hack/start-registry-proxies.sh\nsudo --preserve-env=HOME _out/talosctl-linux-amd64 cluster create \\\n    --provisioner=qemu \\\n    --cidr=172.20.0.0/24 \\\n    --registry-mirror docker.io=http://172.20.0.1:5000 \\\n    --registry-mirror registry.k8s.io=http://172.20.0.1:5001  \\\n    --registry-mirror gcr.io=http://172.20.0.1:5003 \\\n    --registry-mirror ghcr.io=http://172.20.0.1:5004 \\\n    --registry-mirror 127.0.0.1:5005=http://172.20.0.1:5005 \\\n    --install-image=127.0.0.1:5005/siderolabs/installer:<installer-image> \\\n    --controlplanes 3 \\\n    --workers 2 \\\n    --with-bootloader=false \\\n    --disk-preallocate=false \\\n    --config-patch-control-plane=@"${PWD}/hack/test/patches/etcd-version.yaml"\n\n# compile the tests\nmake _out/integration-test-linux-amd64\n\n\n##################################################################\n# ACTUAL TESTS - this might need to be repeated few times\n##################################################################\n# run ETCD tests\nsudo -E _out/integration-test-linux-amd64 \\\n    -test.v -talos.provisioner=qemu \\\n    -talos.talosctlpath=$PWD/_out/talosctl-linux-amd64 \\\n    -talos.kubectlpath=$PWD/_out/kubectl  \\\n    -talos.helmpath=$PWD/_out/helm \\\n    -talos.kubestrpath=$PWD/_out/kubestr \\\n    -test.run TestIntegration/api.Etcd\n\n# run Reboot tests\nsudo -E _out/integration-test-linux-amd64 \\\n    -test.v -talos.provisioner=qemu \\\n    -talos.talosctlpath=$PWD/_out/talosctl-linux-amd64 \\\n    -talos.kubectlpath=$PWD/_out/kubectl  \\\n    -talos.helmpath=$PWD/_out/helm \\\n    -talos.kubestrpath=$PWD/_out/kubestr \\\n    -test.run TestIntegration/api.Etcd\n##################################################################\n# END TESTS\n##################################################################\n\n# (optional) get ETCD logs\nsudo -E _out/talosctl-linux-amd64 logs etcd --nodes=<node-ip>\n# (optional) get ETCD status\nsudo -E _out/talosctl-linux-amd64 etcd status --nodes=172.20.0.2,172.20.0.3,172.20.0.4 \n# (optional) get ETCD members\nsudo -E _out/talosctl-linux-amd64 etcd members --nodes=<node-ip>'
    continuous_reproducer = True
